version: '3.8'
services:
  webapp:
    image: mai-webapp:1.1.0
    build: ./mai-webapp/
    tty: true
    stdin_open: true
    ports:
      - "3080:3080"
    networks:
      - mai-net
  gateway:
    image: mai-gateway:1.1.0
    build: ./mai-gateway/
    tty: true
    stdin_open: true
    hostname: mai.gateway.ws
    environment:
      - LIBRE_TRANSLATE_URL=http://mai.translator.ws:5000
      - OPEN_TTS_URL=http://mai.synthesis.ws:5500
    networks:
      - mai-net
  translator:
    image: libretranslate/libretranslate
    tty: true
    stdin_open: true
    hostname: mai.translator.ws
    command: 
      - "--load-only"
      - "fr,en,es"
    networks:
      - mai-net
  synthesis:
    image: synesthesiam/opentts:all
    tty: true
    stdin_open: true
    hostname: mai.synthesis.ws
    networks:
      - mai-net
networks:
  mai-net:
    driver: bridge